### ISSUE TITLE
java.lang.NullPointerException when trying to filter by timerange

### ISSUE THREAD

**Issue by jackyyaplt** [pegasystems/pega-alertanalyzer#6]
After loading the alert log, there is a draggable control below the chart that allows filtering by time. However, it crashes with the following Exception:
@@@@@@@@@
HTTP Status 500 ? Internal Server Error
Type Exception Report
Description The server encountered an unexpected condition that prevented it from fulfilling the request.
Exception
java.lang.NullPointerException
	com.pega.gsea.util.AlertAnalysis.applyDateFilter(AlertAnalysis.java:131)
	com.pega.gsea.servlets.ActionServlet.doPost(ActionServlet.java:174)
	com.pega.gsea.servlets.ActionServlet.doGet(ActionServlet.java:33)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Note The full stack trace of the root cause is available in the server logs.
@@@@@@@@@

### Expected Behavior

The expected behaviour is that all info should be then filtered by the selected date range.

### Current Behavior

In the console, the following error is thrown:
@@@@@@@@@
java.text.ParseException: Unparseable date: "Thu Jan 25 2018 09:17:25  0800 (M"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at com.pega.gsea.servlets.ActionServlet.doPost(ActionServlet.java:146)
        at com.pega.gsea.servlets.ActionServlet.doGet(ActionServlet.java:33)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52
)
@@@@@@@@@

### Context

With this issue, I cannot filter the event by the desired time range.

### Steps to Reproduce (for bugs)

This is repeatable, just load up a alert file, and move the slider below the graph to filter by any date range.

### Your Environment

Windows 7 Enterprise, Tomcat 8.5.24, IE and Chrome both have the errors.

**Comment by dasi1** [comment]
Any updates on this? Still facing the same problem.

**Comment by cdancy** [comment]
@dcasavant @feenr any thoughts here?

**Comment by feenr** [comment]
No idea. I only converted the existing project from Maven to Gradle. I don't mind taking a look at it though.

**Comment by jackyyaplt** [comment]
Hi,
Still same issue.

Thanks and regards,
Jacky

**Comment by feenr** [comment]
@jackyyaplt @dasi1 Care to share an alert log for testing purposes? Had some trouble reproducing the issue with my own alert log.
